const mongoose = require("mongoose");

// Project timeline stores read-only partner activity generated by internal/project actions.
const projectTimelineSchema = new mongoose.Schema(
  {
    projectId: { type: mongoose.Schema.Types.ObjectId, ref: "Project", required: true, index: true },
    eventText: { type: String, required: true, trim: true },
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
  },
  { timestamps: { createdAt: "createdAt", updatedAt: false } }
);

module.exports = mongoose.model("ProjectTimeline", projectTimelineSchema);
